# Generated by Django 2.0.7 on 2021-03-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210311_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='create',
            new_name='created',
        ),
    ]
